import os, sys
os.chdir("D:/addsd/277286/Documents/项目维护与修改/repo_temp")
lines = []
lines.append('"""')
lines.append("RAG 核心模块：文档加载、向量存储与语义检索")
lines.append("")
lines.append("完整 RAG 流程：文档加载 -> 文本分块 -> 向量化入库 -> 语义检索")
lines.append("")
lines.append("依赖: langchain-community, chromadb, sentence-transformers, pypdf")
lines.append('"""')
lines.append("")
lines.append("import os")
lines.append("from typing import List, Optional")
lines.append("")
lines.append("from dotenv import load_dotenv")
lines.append("from langchain.text_splitter import RecursiveCharacterTextSplitter")
lines.append("from langchain.schema import Document")
lines.append("from langchain_community.document_loaders import PyPDFLoader, TextLoader")
lines.append("from langchain_community.embeddings import HuggingFaceEmbeddings")
lines.append("from langchain_chroma import Chroma")
lines.append("")
lines.append("load_dotenv()")
lines.append("")
lines.append("")
lines.append('def _get_env(key, default=""):')
lines.append('    """安全读取环境变量，返回 strip 后的值或默认值。"""')
lines.append("    return os.getenv(key, default).strip()")
lines.append("")
lines.append("")
lines.append("# ---------- 文档加载 ----------")
lines.append("")
lines.append("def load_documents(docs_dir=None):")
lines.append('    """')
lines.append("    从指定目录加载所有 PDF 和 TXT 文件。")
lines.append("    ")
lines.append("    参数说明：")
lines.append("        docs_dir: 文档目录路径，默认从环境变量 DOCS_DIR 读取")
lines.append("    ")
lines.append("    返回：LangChain Document 列表")
lines.append('    """')
lines.append('    if docs_dir is None:')
lines.append('        docs_dir = _get_env("DOCS_DIR", "./data/docs")')
lines.append("    docs_dir = os.path.abspath(docs_dir)")
lines.append("    if not os.path.isdir(docs_dir):")
lines.append("        os.makedirs(docs_dir, exist_ok=True)")
lines.append("        return []")
lines.append("    documents = []")
lines.append('    supported_ext = (".pdf", ".txt")')
lines.append("    for filename in sorted(os.listdir(docs_dir)):")
lines.append("        filepath = os.path.join(docs_dir, filename)")
lines.append("        ext = os.path.splitext(filename)[1].lower()")
lines.append("        if ext not in supported_ext:")
lines.append("            continue")
lines.append("        try:")
lines.append('            if ext == ".pdf":')
lines.append("                loader = PyPDFLoader(filepath)")
lines.append("                docs = loader.load()")
lines.append("            else:")
lines.append('                loader = TextLoader(filepath, encoding="utf-8")')
lines.append("                docs = loader.load()")
lines.append("            for doc in docs:")
lines.append('                doc.metadata["source_file"] = filename')
lines.append('                doc.metadata["source_path"] = filepath')
lines.append("            documents.extend(docs)")
lines.append('            print(f"  OK 已加载 {filename} ({len(docs)} 页)")')
lines.append("        except Exception as e:")
lines.append('            print(f"  FAIL 加载失败: {filename} - {e}")')
lines.append("    return documents")
lines.append("")
lines.append("")
lines.append("# ---------- 文本分块 ----------")
lines.append("")
lines.append("def split_documents(documents, chunk_size=None, chunk_overlap=None):")
lines.append('    """')
lines.append("    将文档按中文标点优先策略递归切分为固定大小的文本块。")
lines.append("    ")
lines.append("    参数说明：")
lines.append("        documents: 原始文档列表")
lines.append("        chunk_size: 每块字符数")
lines.append("        chunk_overlap: 块间重叠字符数")
lines.append("    ")
lines.append("    返回：切分后的 Document 列表")
lines.append('    """')
lines.append("    if not documents:")
lines.append("        return []")
lines.append("    if chunk_size is None:")
lines.append('        chunk_size = int(_get_env("CHUNK_SIZE", "500"))')
lines.append("    if chunk_overlap is None:")
lines.append('        chunk_overlap = int(_get_env("CHUNK_OVERLAP", "100"))')
lines.append("    splitter = RecursiveCharacterTextSplitter(")
lines.append("        chunk_size=chunk_size,")
lines.append("        chunk_overlap=chunk_overlap,")
lines.append('        separators=["\\n\\n", "\\n", "\\u3002", "\\uff01", "\\uff1f", ". ", "! ", "? ", "\\uff0c", ", ", " ", ""],')
lines.append("        length_function=len,")
lines.append("    )")
lines.append("    chunks = splitter.split_documents(documents)")
lines.append('    print(f"  -> 切分为 {len(chunks)} 个文本块")')
lines.append("    return chunks")
lines.append("")
lines.append("")
lines.append("# ---------- 向量化与存储 ----------")
lines.append("")
lines.append("def get_embeddings(model_name=None):")
lines.append('    """获取 HuggingFace 嵌入模型实例。"""')
lines.append("    if model_name is None:")
lines.append('        model_name = _get_env("EMBEDDING_MODEL_NAME", "BAAI/bge-small-zh-v1.5")')
lines.append("    return HuggingFaceEmbeddings(")
lines.append("        model_name=model_name,")
lines.append('        model_kwargs={"device": "cpu"},')
lines.append('        encode_kwargs={"normalize_embeddings": True},')
lines.append("    )")
lines.append("")
lines.append("")
lines.append("def get_vector_store(persist_dir=None, embedding_model=None):")
lines.append('    """加载或创建 Chroma 向量数据库实例。"""')
lines.append("    if persist_dir is None:")
lines.append('        persist_dir = _get_env("CHROMA_DB_DIR", "./chroma_db")')
lines.append("    if embedding_model is None:")
lines.append("        embedding_model = get_embeddings()")
lines.append("    return Chroma(")
lines.append("        persist_directory=persist_dir,")
lines.append("        embedding_function=embedding_model,")
lines.append('        collection_name="local_rag_knowledge",')
lines.append("    )")
lines.append("")
lines.append("")
lines.append("def ingest_documents(docs_dir=None, chunk_size=None, chunk_overlap=None, persist_dir=None):")
lines.append('    """')
lines.append("    完整的「加载 -> 切分 -> 入库」流水线。")
lines.append("    ")
lines.append("    返回：入库的文本块数量")
lines.append('    """')
lines.append('    print("=" * 50)')
lines.append('    print("开始文档入库流程...")')
lines.append('    print("=" * 50)')
lines.append("    docs = load_documents(docs_dir)")
lines.append("    if not docs:")
lines.append('        print("未找到任何文档")')
lines.append("        return 0")
lines.append("    chunks = split_documents(docs, chunk_size, chunk_overlap)")
lines.append("    embedding_model = get_embeddings()")
lines.append("    if persist_dir is None:")
lines.append('        persist_dir = _get_env("CHROMA_DB_DIR", "./chroma_db")')
lines.append('    print(f"  -> 向量化并写入 Chroma ...")')
lines.append("    Chroma.from_documents(")
lines.append("        documents=chunks,")
lines.append("        embedding=embedding_model,")
lines.append("        persist_directory=persist_dir,")
lines.append('        collection_name="local_rag_knowledge",')
lines.append("    )")
lines.append('    print(f"  OK 入库完成，共 {len(chunks)} 个文本块")')
lines.append("    return len(chunks)")
lines.append("")
lines.append("")
lines.append("# ---------- 语义检索 ----------")
lines.append("")
lines.append("def retrieve_context(query, k=None, store=None, persist_dir=None):")
lines.append('    """')
lines.append("    对用户问题进行语义检索，返回最相关的 k 个文档片段。")
lines.append("    ")
lines.append("    返回：按相关性降序排列的 Document 列表")
lines.append('    """')
lines.append('    if k is None:')
lines.append('        k = int(_get_env("RETRIEVAL_TOP_K", "4"))')
lines.append("    if store is None:")
lines.append("        if persist_dir is None:")
lines.append('            persist_dir = _get_env("CHROMA_DB_DIR", "./chroma_db")')
lines.append("        store = get_vector_store(persist_dir)")
lines.append("    results = store.similarity_search_with_relevance_scores(query, k=k)")
lines.append("    filtered = [doc for doc, score in results if score >= 0.3]")
lines.append("    if not filtered:")
lines.append("        filtered = [doc for doc, _ in results[:2]]")
lines.append("    return filtered")
lines.append("")
lines.append("")
lines.append("# ---------- 幻觉抑制 Prompt 模板 ----------")
lines.append("")
lines.append('HALLUCINATION_SUPPRESSION_PROMPT = """你是专业、严谨的知识库问答助手。\n\n约束规则：\n1. 仅使用参考文档中的信息进行回答\n2. 文档信息不足时明确告知无法回答\n3. 禁止编造文档中未包含的内容\n\n【参考文档】\n{context}\n"""')
lines.append("")
lines.append("")
lines.append('if __name__ == "__main__":')
lines.append("    import sys")
lines.append('    cmd = sys.argv[1] if len(sys.argv) > 1 else "ingest"')
lines.append('    if cmd == "ingest":')
lines.append("        ingest_documents()")
lines.append('    elif cmd == "retrieve":')
lines.append('        q = sys.argv[2] if len(sys.argv) > 2 else "测试问题"')
lines.append("        docs = retrieve_context(q)")
lines.append('        print(f"检索到 {len(docs)} 个相关片段")')
lines.append("        for i, d in enumerate(docs, 1):")
lines.append('            src = d.metadata.get("source_file", "unknown")')
lines.append('            print(f"--- 片段 {i} (来源: {src}) ---")')
lines.append("            print(d.page_content[:200])")
lines.append("            print()")

with open("rag_core.py", "w", encoding="utf-8") as f:
    f.write("\n".join(lines) + "\n")
print("Script written.")
